### ISSUE TITLE
Cannot Import Files with 2018.1.1

### ISSUE THREAD

**Issue by christopherwxyz** [mark-keaton/NetSuiteSDF#11] opened 2018-05-14 14:56 UTC
```
[INFO] --- exec-maven-plugin:1.5.0:java (default-cli) @ sdf-cli ---
SuiteCloud Development Framework CLI (com.netsuite.ide.core_2018.1.1)
Using token based authentication.
Existing files will be overwritten, do you want to continue? Type YES to continue.
Cancelled.
```

Using the quick action to Import Files, selecting a JS file to import results in a `Cancelled.` return. Does not import the target file.

**Comment by christopherwxyz** [comment] 2018-05-29 14:55
No progress. Will review by end of week.

**Comment by mark-keaton** [comment] 2018-11-06 22:01
@christopherwxyz can you confirm same is happening in 0.4.0?

**Comment by JonnyBoy333** [comment] 2018-11-07 15:48
I can confirm this is still happening. I'm looking into it but it happens when you are using tokens instead of credentials. The extension still asks for your password even though sdfcli does not, which leads to your password being output when sdfcli asks "Would you like to override existing objects?". 

So unless your password is coincidentally the word "YES", the import gets canceled. I'm looking into a way to conditionally ask for the password. It's a little more difficult than you might expect because the terminal outputs go through a stream in chunks and the timing of when to prompt for a password is a little unclear. I'll see what I can come up with.

**Comment by mark-keaton** [comment] 2018-11-14 15:57
@JonnyBoy333 

Your fix is in the Marketplace. Is this resolved?

**Closed** 2018-12-10 15:17 UTC
Labels: bug
